apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-app-demo
  labels:
    app.tanzu.vmware.com/workload-type: web
spec:
  source:
    git:
      url: https://github.com/beeNotice/tanzu-app
      ref:
        branch: main
