AVI_CA_DATA_B64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1akNDQXM2Z0F3SUJBZ0lVYlY2WkRWY1FzTmhOTExmTEMrSHF1dkZjQ1lBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2daWXhDekFKQmdOVkJBWVRBbFZUTVFzd0NRWURWUVFJREFKRFFURVNNQkFHQTFVRUJ3d0pVR0ZzYnlCQgpiSFJ2TVF3d0NnWURWUVFLREFOUVJWb3hEREFLQmdOVkJBc01BMUJGV2pFa01DSUdBMVVFQXd3YllYWnBMbWhoCllYTXRORGc1TG5CbGVpNTJiWGRoY21VdVkyOXRNU1F3SWdZSktvWklodmNOQVFrQkZoVndaWHB6ZFhCd2IzSjAKUUhadGQyRnlaUzVqYjIwd0hoY05NakV4TVRBNU1UUXpNalUxV2hjTk1qSXhNVEE1TVRRek1qVTFXakNCbGpFTApNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdNQWtOQk1SSXdFQVlEVlFRSERBbFFZV3h2SUVGc2RHOHhEREFLCkJnTlZCQW9NQTFCRldqRU1NQW9HQTFVRUN3d0RVRVZhTVNRd0lnWURWUVFEREJ0aGRta3VhR0ZoY3kwME9Ea3UKY0dWNkxuWnRkMkZ5WlM1amIyMHhKREFpQmdrcWhraUc5dzBCQ1FFV0ZYQmxlbk4xY0hCdmNuUkFkbTEzWVhKbApMbU52YlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGJBdnlyaGhpVmhTNDFECnYrOVZjR1M5bW0xSnk4NGk5cW9ZTlFDUUpmS2Jwd0dqUTV6a0RUVDZybUxIRy9ERi85bjJOZUhyR1p0MlRtbmsKTG9LdUpnbmpHT2ZPNFl0ZXR5MlVEQlNWUTB4Z1BzUmVqbkIyaXhoekFUbUcydmYxUFVPTXBrdFZtemFHOGxRQwpTZ1JzeEl3RmN1QzdWUHR0QkkzZjRXTlhCVXpjcXBDREJGOEJuM1VjeUFPcWdRUWdKWGpJcjlMakdPMGd1d2NzCkZ2ZDVhVFVNRzFOU0J6anA0bGR5SWszVlR4VlM4QXhTVkYrOVB2dm9MdVRJWUt3STlTRmxZN2o2RHc0QUx6YW0KSEp5SjdFRjNnMDROdnRvaG1WeGMyNE9UcUFkL2pXMks1UDhTYnkwSnhFRHR4UnFxdDdkd1cwUDVmd1RaQm0rVgpQVkd0NFBNQ0F3RUFBYU1xTUNnd0pnWURWUjBSQkI4d0hZSWJZWFpwTG1oaFlYTXRORGc1TG5CbGVpNTJiWGRoCmNtVXVZMjl0TUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCYXZLN3VUTTh5S29VVlRnVS9pMndJUWVXU0p3cVoKemg5MG5Oa1FTVE5KTmJ3Wjl0ZFNIeXpnMWlrOEQ1R0Z0NVJnTVdKNE9DWE1NSXhvanYyYWZmQlpuMldOSWN6MQpkRkVjd2hybnAyMzgydGU1WXRscXFCTit5ZHAxS1labGh6Y1h4OGYxT3FxbWJtcWt6UG9ZTUo5V0NwNERXR2V1CmNWb3pCSUh3T21xVk5XR3IxaXJSZjVLOGliaWJ0RDUyZk9XU01KSkJTTW40RGNHOC9GcnlxdElFWTc3d2lORGEKU0FkamZuZkpkMDF1d0U0NVNvc1J6bFVlbCtMSHVSRGtHOU5sV3dBZE44QXA3L2xweTd3dWhRaWZmYnlQbjRXTApFM2ZobHRQZjBVTmM0QTMvREJYbDZqTzVRdkhSNW4zV0cwdUhTUk9iMDJLN3hUcXRDdkNYa2I3dgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
AVI_CONTROL_PLANE_HA_PROVIDER: "true"
AVI_CLOUD_NAME: Default-Cloud
AVI_CONTROLLER: avi.haas-489.pez.vmware.com
AVI_DATA_NETWORK: Extra
AVI_DATA_NETWORK_CIDR: 10.213.73.0/24
AVI_ENABLE: "true"
AVI_LABELS: ""
AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_CIDR: 10.213.73.0/24
AVI_MANAGEMENT_CLUSTER_VIP_NETWORK_NAME: Extra
AVI_PASSWORD: <encoded:eW9obGI4YmJtOTBtMWZGQnhuIQ==>
AVI_SERVICE_ENGINE_GROUP: Default-Group
AVI_USERNAME: admin
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_PLAN: dev
ENABLE_AUDIT_LOGGING: "false"
ENABLE_CEIP_PARTICIPATION: "false"
ENABLE_MHC: "true"
IDENTITY_MANAGEMENT_TYPE: none
INFRASTRUCTURE_PROVIDER: vsphere
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
OIDC_IDENTITY_PROVIDER_CLIENT_ID: ""
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: ""
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: ""
OIDC_IDENTITY_PROVIDER_ISSUER_URL: ""
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: ""
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: ""
OS_ARCH: amd64
OS_NAME: photon
OS_VERSION: "3"
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
VSPHERE_CONTROL_PLANE_DISK_GIB: "40"
VSPHERE_CONTROL_PLANE_MEM_MIB: "8192"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "2"
VSPHERE_DATACENTER: /Datacenter
VSPHERE_DATASTORE: /Datacenter/datastore/LUN01
VSPHERE_FOLDER: /Datacenter/vm
VSPHERE_NETWORK: Extra
VSPHERE_PASSWORD: <encoded:eW9obGI4YmJtOTBtMWZGQnhuIQ==>
VSPHERE_RESOURCE_POOL: /Datacenter/host/Cluster/Resources
VSPHERE_SERVER: vcsa-01.haas-489.pez.vmware.com
VSPHERE_SSH_AUTHORIZED_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCxMAW0ZZ/0PFhQxkKiH5Zsj9QoOF7GiRz2HCjgKNmrtQD6H6OxkkMSTMIG/DeOPS1odOZD8iAmf7yBLq6sA+SPeHuyvjVDerffqA6YeG3uR+aYtBcoM/WmGvELKxWGZ2olWjtn0QPIniWqGrLTk6u236K4aiq9R3wWHsAYHnGLxaQVhFUGIeOAAu4jcVfYUBDstJF9s6AIGt8QDzs2hIuez7KXTbensVSZC9Z3WYF6hOAZujBTJ+pMW8cTIDLOuF2yXIs5YE/9ETC8oxxWzKucbL/7YUwerPETaCvxLjO5ITCRf3L4MuvhZCUGOTz7iuzVdByFYAZTLS2ktdqq3B/7
VSPHERE_TLS_THUMBPRINT: 4D:70:F5:9A:B9:B0:09:81:04:38:C9:16:80:62:3B:36:E1:28:EB:13
VSPHERE_USERNAME: administrator@vsphere.local
VSPHERE_WORKER_DISK_GIB: "40"
VSPHERE_WORKER_MEM_MIB: "8192"
VSPHERE_WORKER_NUM_CPUS: "2"

