apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  namespace: test
  name: sample-app
spec:
  cluster:
    namespace: test
  serviceAccountName: default-ns-sa
  fetch:
  # https://github.com/beeNotice/tanzu-tools/tree/main/tap/supply-chain/kapp-ytt
  - git:
      url: https://github.com/beeNotice/tanzu-tools
      ref: origin/main
      subPath: tap/supply-chain/kapp-ytt
  template:
  - ytt: {}
  deploy:
  - kapp: {}
