apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  namespace: prod
  name: scg-deploy
  labels:
    app.kubernetes.io/component: deliverable
    app.kubernetes.io/part-of: tanzu-app
    app.tanzu.vmware.com/deliverable-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    carto.run/cluster-template-name: deliverable-template
    carto.run/resource-name: deliverable
    carto.run/supply-chain-name: source-test-scan-to-url
    carto.run/template-kind: ClusterTemplate
    carto.run/workload-name: tanzu-app-deploy
    carto.run/workload-namespace: dev
spec:
  params:
  - name: gitops_ssh_secret
    value: git-ssh
  - name: gitops_sub_path
    value: config/scg
  source:
    git:
      url: ssh://git@github.com/beeNotice/tanzu-app-deploy.git
      ref:
        branch: main
