apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: fmartin-cluster
  namespace: fmartin
spec:
  distribution:
    version: v1.20.9
  topology:
    controlPlane:
      count: 1
      class: best-effort-small
      storageClass: tanzu
    workers:
      count: 1
      class: best-effort-large
      storageClass: tanzu
  settings:
    storage:
      defaultClass: tanzu
