apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: VSphereMachineTemplate
metadata:
  annotations:
  generation: 1
  name: tkg-cluster-1-worker-updated
  namespace: default
spec:
  template:
    spec:
      cloneMode: fullClone
      datacenter: /Datacenter
      datastore: /Datacenter/datastore/LUN01
      diskGiB: 40
      folder: /Datacenter/vm
      memoryMiB: 16384
      network:
        devices:
        - dhcp4: true
          networkName: Extra
      numCPUs: 4
      resourcePool: /Datacenter/host/Cluster/Resources
      server: vcsa-01.haas-489.pez.vmware.com
      storagePolicyName: ""
      template: /Datacenter/vm/photon-3-kube-v1.21.2+vmware.1-tkg
