---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: blue
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: harbor.withtanzu.com/fmartin/mirror/nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: green
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: harbor.withtanzu.com/fmartin/mirror/nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: blue
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: green
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
