apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  namespace: prod
  name: tanzu-app-deploy
  labels:
    app.tanzu.vmware.com/deliverable-type: web
spec:
  params:
    - name: gitops_ssh_secret
      value: git-ssh
  source:
    git:
      url: ssh://git@github.com/beeNotice/tanzu-app-deploy
      ref:
        branch: main
