apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: life-recette
  name: life-recette-admin
rules:
  # kubectl api-resources -o wide
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
