apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: example-nfs
provisioner: cluster.local/nfs-ganesha-server-nfs-server-provisioner
parameters:
  server: 10.213.73.203
  path: /mnt/nfs_share
  readOnly: "false"
